### ISSUE TITLE
Start Bluetooth

### ISSUE THREAD

**Issue by alesoft73** [whiskerz007/proxmox_hassio_lxc#14]
IN witch mode i can start to use bluetooth ??

**Comment by whiskerz007** [comment]
At this time, bluetooth devices are not able to passthrough to the LXC. If you need bluetooth functionality, the current viable option is to use the VM.

**Comment by alesoft73** [comment]
Ok i attend, but i have the same problem in a VM ;)

**Comment by whiskerz007** [comment]
Assistance with VM problems will not be addressed here.
