### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by lukashaensel** [whiskerz007/proxmox_hassio_lxc#19]
root@server:~# bash -c "$(wget -qLO - https://github.com/whiskerz007/proxmox_hassio_lxc/raw/master/create_container.sh)"
[INFO] Using 'local-lvm' for storage location.
[INFO] Container ID is 100.
Updating LXC template list...
Downloading LXC template...
Creating LXC container...
Starting LXC container...
Setting up container OS...
Updating container OS...
Installing prerequisites...
Installing Docker...
Customizing Docker...
Installing Home Assistant...
[ERROR:LXC] 2@63 Unknown failure occured.
[ERROR] 2@165 Unknown failure occured.
  Logical volume "vm-100-disk-0" successfully removed

Can you help me?

**Comment by det-peralta** [comment]
+1

**Comment by tteck** [comment]
From wiskerz007, "It seems the HA devs have updated the files I target and changed the name. I'm in the process of moving and when I get settled in, I'll have an update pushed out."

**Comment by whiskerz007** [comment]
94649045fb7783b5be1ad6826a83acd946b3e11e commit has resolved this issue.
