### ISSUE TITLE
How to hook up the Wyze sensor bridge?

### ISSUE THREAD

**Issue by rakeshdas1** [whiskerz007/proxmox_hassio_lxc#26]
I want to use my Wyze sensors with HassIO with the [HA-Wyzesense](https://github.com/kevinvincent/ha-wyzesense) plugin. I plugged in the sensor bridge into my Proxmox machine and verified that the device is recognized by running `lsusb` on my Proxmox host. 

Output of `lsusb`:

```
Bus 002 Device 002: ID 8087:8000 Intel Corp. 
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 8087:8008 Intel Corp. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 003: ID 1a86:e024 QinHeng Electronics 
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

Next, I ran this command outlined in the Readme to update the device hooks:  `bash -c "$(wget -qLO - https://github.com/whiskerz007/proxmox_hassio_lxc/raw/master/set_autodev_hook.sh)" -s 100`

When I rebooted HassIO, I went into the shell and checked the `/dev` directory, but I couldn't find a `hidraw0` device.

Did I miss a step somewhere?

**Comment by pi642s** [comment]
hmm for me i do find the hidraw0 but for some reasons can't set wyze sensor

`root@homeassistant:/usr/share/hassio# dmesg | grep hidraw
[    1.451477] hidraw: raw HID events driver (C) Jiri Kosina
[    1.548144] hid-generic 0018:045E:0914.0001: hidraw0: I2C HID v1.00 Device [MSHW0030:00 045E:0914] on i2c-MSHW0030:00
[    2.094338] hid-generic 0003:1A86:E024.0002: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1.2/input0
[    2.347135] hid-generic 0003:045E:07CD.0003: input,hiddev1,hidraw1: USB HID v1.11 Keyboard [Microsoft Surface Keyboard] on usb-0000:00:14.0-1.4/input0
[    5.502710] hid-multitouch 0003:045E:07CD.0003: input,hiddev1,hidraw1: USB HID v1.11 Keyboard [Microsoft Surface Keyboard] on usb-0000:00:14.0-1.4/input0
[  702.270731] hid-generic 0003:1A86:E024.0004: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1.2/input0
root@homeassistant:/usr/share/hassio# `

**Comment by rakeshdas1** [comment]
@pi642s Interesting, how did you get your container to mount `/dev/hidraw0`? Did you have to put something in the container's configuration file manually?

**Comment by pi642s** [comment]
yup, same here!

**Comment by whiskerz007** [comment]
I have recently push a change to `set_autodev_hook.sh` that might resolve you problem. Please follow the instructions [here](https://github.com/whiskerz007/proxmox_hassio_lxc#update-device-hooks) and report back if this did, or did not, resolve the problem.

**Comment by rakeshdas1** [comment]
Thanks @whiskerz007, I'll try it and report back!

**Comment by whiskerz007** [comment]
What is the results from running `ls -l /dev/hidraw*`?

**Comment by rakeshdas1** [comment]
Output: `ls: cannot access '/dev/hidraw*': No such file or directory`

**Comment by whiskerz007** [comment]
@rakeshdas1 Was that reply from running the command in the LXC or from Proxmox shell. The response that is needed is from Proxmox shell.

**Comment by rakeshdas1** [comment]
My bad, the output above is from the container, the Proxmox shell outputs the following:

`crw------- 1 root root 242, 0 May 27 11:35 /dev/hidraw0`

**Comment by whiskerz007** [comment]
@rakeshdas1 Please verify that you have followed the instructions [here](https://github.com/whiskerz007/proxmox_hassio_lxc#update-device-hooks) (making sure to change the `100` at the end of the script to the ID of your LXC), rebooted the container, and are still having the problem?

**Comment by rakeshdas1** [comment]
@whiskerz007 Another run of the script solved the issue, thanks for helping me debug!
