### ISSUE TITLE
Node-Red addon won't start

### ISSUE THREAD

**Issue by jeremeyi** [whiskerz007/proxmox_hassio_lxc#3]
I installed this on my proxmox 5.4-13 machine last night and started messing with it today and when I try to start the node-red addon it won't start and gives this in the system logs in hassio "Can't start addon_a0d7b954_nodered: 500 Server Error: Internal Server Error ("error gathering device information while adding custom device "/dev/mem": no such file or directory").  I was also having trouble with my Aeotec Z-Stick but figured it was just me not knowing how to pass it to a lxc. 

Pretty excited to see you working on a lxc script for this!  Been using your vm version for some time now thanks for the hard work!

**Comment by etamtlosz** [comment]
I can't replicate this. I've just installed and started nodered on my dev container.
Did you use the latest version of the script? As far as I can see there are some changes related to "/dev/mem" in the last version.

**Comment by jeremeyi** [comment]
It was not the latest version of the script it was one version earlier,  I saw those changes and thought it might fix the problem, but when I try to install the latest version I get an error.

[INFO] Using 'local-lvm' for storage location.
[INFO] Container ID is 106.
Updating LXC template list...
Downloading LXC template...
Creating LXC container...
Starting LXC container...
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to create bus connection: Host is down
[ERROR] 1@145 Unknown failure occured.
Logical volume "vm-106-disk-0" successfully removed

**Comment by whiskerz007** [comment]
@jeremeyi The new error you're experiencing is related to #1. I have pushed a new commit which should resolve this problem. Please report your experience with the latest commit.

**Comment by jeremeyi** [comment]
Yep, both node-red not starting and the issue with the script not installing (System has not been booted with systemd as init system (PID 1). Can't operate.) seem to be resolved.
Now for a newbie question, my usb zwave stick.  I can see it in the debian host lxc created by your script.

lsusb
Bus 001 Device 003: ID 0658:0200 Sigma Designs, Inc. Aeotec Z-Stick Gen5 (ZW090) - UZB

ls -l /dev/bus/usb/001/004
crw-r--r-- 1 root root 189, 3 Nov 19 21:02 /dev/bus/usb/001/004

that is the output within the lxc.

What do I need to do for the hassio docker container to see it?

**Comment by jeremeyi** [comment]
Sorry, my bad, I didn't catch that the zwave stick had changed id's from my VM install, once I caught that and changed it in my configuration for the lxc version the zwave stick works fine.  All appears to be working so far.

**Comment by meichthys** [comment]
@whiskerz007 @jeremeyi  I believe this issue can be closed.
