### ISSUE TITLE
Enhancement: Add the ability to configure some settings during install

### ISSUE THREAD

**Issue by borpin** [whiskerz007/proxmox_hassio_lxc#33]
Really like this.

It would be useful to be able to configure the hostname as part of the install rather than having to do it afterwards. Perhaps ask the user for the hostname with a default on RTN and a quiet mode that just uses defaults.

https://github.com/whiskerz007/proxmox_hassio_lxc/blob/fad821e2c3d2d0fb570f844379f03b247ff3b9c7/create_container.sh#L124

Personally, I always use a fixed IP, so the option for that to be requested during the install would be useful.

I realise these things can be changed, but if they can be done as part of the install, all the better.

**Comment by whiskerz007** [comment]
One of the reasons the hostname is not user fillable is to encourage the use of the Proxmox UI. There is a case to be made to include it in the install script, however maybe better documentation would suffice.
