### ISSUE TITLE
I've forked this for a generic LXD install on Ubuntu Server (and theoretically any OS that is able to run it)

### ISSUE THREAD

**Issue by thiscantbeserious** [whiskerz007/proxmox_hassio_lxc#37]
This is currently hardcoded to aarch64 and it only works after the first restart (no clue why, the kernel modules are theoretically loaded trought lxd config) ... so it's still a work in progress. 

https://github.com/thiscantbeserious/lxd_homeassistant_install/blob/master/README.md

No clue how to contact you otherwise so I've opened this "issue". 

Cheers!

**Comment by whiskerz007** [comment]
If I understand your issue, HA works when you run the LXD for the first time. Every subsequent reboot of the LXD HA fails to properly start. If you reboot your host machine and start the LXD, it'll run the first time from a clean boot of the host, but not any subsequent reboot of the LXD until the host reboots. This is a problem with the LXD guest OS sharing the BTIME value of the host OS. HA relies on BTIME to decide what containers to start. The BTIME server I created is used to trick HA supervisor into thinking it is a new boot. I'd be happy to assist with developing your LXD implementation if there is any interest.

**Comment by xiki808** [comment]
Would love to see a script for an installation on a plain LXD. I used the script but with some hiccups, for example addon containers not starting after restart and USB passthrough seems to take time to be found by HA
