### ISSUE TITLE
Can't start after reboot

### ISSUE THREAD

**Issue by weert14** [whiskerz007/proxmox_hassio_lxc#6]
Hello,

The container installs fine with the script. But when i shutdown the container and want to start it again it does not start anymore. Can you help me please?

`root@straussie:~# systemctl status pve-container@100.service
● pve-container@100.service - PVE LXC Container: 100
   Loaded: loaded (/lib/systemd/system/pve-container@.service; static; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2019-11-26 19:19:43 CET; 8min ago
     Docs: man:lxc-start
           man:lxc
           man:pct
  Process: 2354 ExecStart=/usr/bin/lxc-start -n 100 (code=exited, status=1/FAILURE)

Nov 26 19:19:42 straussie systemd[1]: Starting PVE LXC Container: 100...
Nov 26 19:19:43 straussie lxc-start[2354]: lxc-start: 100: lxccontainer.c: wait_on_daemonized_start: 865 No such file or directory - Failed to receive the container state
Nov 26 19:19:43 straussie lxc-start[2354]: lxc-start: 100: tools/lxc_start.c: main: 329 The container failed to start
Nov 26 19:19:43 straussie lxc-start[2354]: lxc-start: 100: tools/lxc_start.c: main: 332 To get more details, run the container in foreground mode
Nov 26 19:19:43 straussie lxc-start[2354]: lxc-start: 100: tools/lxc_start.c: main: 335 Additional information can be obtained by setting the --logfile and --logpriority 
Nov 26 19:19:43 straussie systemd[1]: pve-container@100.service: Control process exited, code=exited, status=1/FAILURE
Nov 26 19:19:43 straussie systemd[1]: pve-container@100.service: Failed with result 'exit-code'.
Nov 26 19:19:43 straussie systemd[1]: Failed to start PVE LXC Container: 100.`

**Comment by meichthys** [comment]
@weert14  Are you still having this issue? If not, could you close this issue?
If you are still having this issue please make sure proxmox is completely up to date before running the script.

**Comment by weert14** [comment]
It was the issue that my proxmox and debian where up to date. I had to change the version from 10 to 11 in de debian.pm file
