### ISSUE TITLE
HASSIO Command Line

### ISSUE THREAD

**Issue by gdreelin** [whiskerz007/proxmox_hassio_lxc#7]
Whiskerz007 this LXC version is way faster than the original VM version but how do you get the HASSIO Command Line now to do things like snapshots fixes, homeassistant check, etc? If the machine binds up for some reason this was area to fix all those issue.

**Comment by jeremeyi** [comment]
I have an older version of the script running but I am able to access the CLI via the ssh add on in hass.io (and a different port than the ssh into the host system).  Is there a reason to update to htis version of the script or is ssh access to the cli the same?

**Comment by whiskerz007** [comment]
I have made `hassio-cli` accessible to the main container. With the new revision of the script, you can open the console, of the container, in Proxmox and run `hassio-cli` at the prompt.

**Comment by jeremeyi** [comment]
So as long as I can get to a core-ssh hass.io login through ssh the only thing I am missing is I can't access the cli from a console within proxmox right?

**Comment by whiskerz007** [comment]
That sounds accurate to me.
