### ISSUE TITLE
Hass.io Add-on installs fail

### ISSUE THREAD

**Issue by heytcass** [whiskerz007/proxmox_hassio_lxc#9]
Tried the VSCode add-on and the SSH/Terminal add-on, and both installs failed.

Both give this error:

`Can't install hassioaddons/ssh-amd64:6.4.1 -> 500 Server Error: Internal Server Error ("Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)").`

Network setup is using static IP from Proxmox. Logging in through the console from the Proxmox UI I can ping 1.1.1.1 without problem from inside the container, so internet seems to be reachable.

**Comment by whiskerz007** [comment]
Try resizing the container. Add 1-2 GB to the root disk and try to install the addon again.

**Comment by heytcass** [comment]
Tried that. Still no luck. Issue is definitely with networking. Blew away the container and started fresh with a DHCP-assigned address and add-ons installed fine. But once I shut down and put it on the correct VLAN and subnet, then got the same error. This is the same VLAN and subnet (and static IP) that I used the full VM on wihtout issue.

**Comment by whiskerz007** [comment]
Have you been able to resolve this issue?

**Comment by heytcass** [comment]
I was not. But I am on ZFS, could the fallocate issue be the problem?

**Comment by whiskerz007** [comment]
ZFS will not affect network communications. The problems I have seen with `fallocate` on a ZFS disk is a failure to start new addons that use the mentioned syscall. Feel free to send a picture of the network settings for your container. I am able to install VSCode and both SSH/Terminal addons on a new LXC container created by the script. Keep in mind, the script create a disk for the LXC that is very small. This is done to give the end user the ability to size the disk to their specification. Increase the size of the disk before proceeding with configuring your Hass.io instance.

**Comment by heytcass** [comment]
I will give it a try tonight and post results.

**Comment by heytcass** [comment]
After an installation error last night, I finally got it back going again tonight, but still have the same issue.

Increased disk size to 240 GB and RAM to 2 GB as seen in the attached screenshot. Can ping out to internet through the console without issue, as seen in the screenshot. But still get the same error in the logs when trying to install the SSH community add-on on a fresh install with nothing configured, also attached.
![Screenshot_20200109_221127](https://user-images.githubusercontent.com/11260288/72123054-085c4b80-332e-11ea-80da-ed62a8c5751e.png)
![Screenshot_20200109_221336](https://user-images.githubusercontent.com/11260288/72123055-085c4b80-332e-11ea-8c46-85b1c1013847.png)
![Screenshot_20200109_221743](https://user-images.githubusercontent.com/11260288/72123056-085c4b80-332e-11ea-9faf-13dd577899ae.png)

**Comment by heytcass** [comment]
Forgot the network settings. Attached.

![Screenshot_20200109_222052](https://user-images.githubusercontent.com/11260288/72123189-70ab2d00-332e-11ea-8437-ced2c623e373.png)

**Comment by whiskerz007** [comment]
@heytcass Are you able to get any addon installed or do they all fail with a similar error?

**Comment by heytcass** [comment]
It seems to be that all add-ons are getting the error.

Just to check, I put the container back to DHCP and everything worked fine. Static mapping seems to be the issue.

**Comment by whiskerz007** [comment]
Please respond with the output of `ip address show dev eth0` and `ip route show` for both DHCP and static network settings of the LXC.

**Comment by heytcass** [comment]
Here you go. File names show which setup leads to each.
![dhcp](https://user-images.githubusercontent.com/11260288/72657646-bc845480-3974-11ea-9874-6bd7a6364e02.png)
![static](https://user-images.githubusercontent.com/11260288/72657647-bc845480-3974-11ea-8819-b046d360463a.png)

**Comment by heytcass** [comment]
Since file names aren't easily seen, first picture (10.0.11.154) is DHCP, second (10.0.11.7) is static.

**Comment by whiskerz007** [comment]
What happens if you set the static IP address to `10.0.11.154/24`?

**Comment by heytcass** [comment]
Now that I've set up another LXC container with just a plain Debian Buster template, the issue seems to be with Proxmox, not your container specifically.

**Comment by whiskerz007** [comment]
Thank you for the follow up.
